global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my_monitor'

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['DOCKER_IP:9090']
- job_name: 'node-exporter'
  static_configs:
  - targets: ['DOCKER_IP:9100']

